api_keys:
  serpapi: "my_serpapi_key"
  serpwow: "my_serpwow_key"
  searchapi: "my_searchapi_key"
  brightdata: "my_brightdata_key"
  scrapingdog: "my_scrapingdog_key"

tor:
  control_password: "controlpass" 
  control_port: 9151
  proxy_port: 9150

api_parameters:
  all:
    max_terms: 5

api_modes:
  - name: "trendspy"
    description: "trendspy"
    api_order:
      - trendspy

  - name: "serpapi"
    description: "serpapi"
    api_order:
      - serpapi

  - name: "brightdata"
    description: "brightdata"
    api_order:
      - brightdata

  - name: "serpwow"
    description: "serpwow"
    api_order:
      - serpwow

  - name: "searchapi"
    description: "searchapi"
    api_order:
      - searchapi

  - name: "applescript_safari"
    description: "applescript_safari"
    api_order:
      - applescript_safari

  - name: "dummy"
    description: "dummy data, no api call"
    api_order:
      - dummy_api

  - name: "smart_tpy"
    description: "trendspy:serpapi:serpwow:searchapi"
    api_order:
      - trendspy
      - serpapi
      - serpwow
      - searchapi

  - name: "smart_pyt"
    description: "NOT IMPLEMENTED! pytrends:serpapi:serpwow:searchapi"
    api_order:
      - pytrends
      - serpapi
      - serpwow
      - searchapi

  - name: "smart_sel"
    description: "selenium:serpapi:serpwow:searchapi"
    api_order:
      - selenium
      - serpapi
      - serpwow
      - searchapi
  
  - name: "smart_pay"
    description: "serpapi:serpwow:searchapi"
    api_order:
      - serpapi
      - serpwow
      - searchapi
