granularity_rules:
  m:
    name: "one-minute"
    freq: "min"
    limit_units: "min"
    limit_value: 4
    search_resolution: "h"
    result_resolution: "m"
    fixed: True
    max_records: 241 # see below for explanation of this value
    record_seconds: 3600
  e:
    name: "eight-minute"
    freq: "8min"
    limit_units: "8min"
    limit_value: 35
    search_resolution: "h"
    result_resolution: "m"
    fixed: True
    max_records: 263 # see below for explanation of this value
    record_seconds: 3600
  n:
    name: "sixteen-minute"
    freq: "16min"
    limit_units: "16min"
    limit_value: 71
    search_resolution: "h"
    result_resolution: "m"
    fixed: True
    max_records: 267 # see below for explanation of this value
    record_seconds: 3600
  h:
    name: "hourly"
    freq: "h"
    search_resolution: "h"
    result_resolution: "h"
    fixed: True
    max_records: 192
    record_seconds: 3600
  D:
    name: "daily"
    freq: "D"
    search_resolution: "D"
    result_resolution: "D"
    fixed: True
    max_records: 270
    record_seconds: 86400
  W:
    name: "weekly"
    freq: "W-SAT" # pandas default for W is a Monday-Sunday week, but we want a Sunday-Saturday week
    search_resolution: "D"
    result_resolution: "D"
    fixed: False # a weekly frequency is not merely a 7 day duration, it's based on the calendar week
    max_records: 270 # 269 weeks + 1 for including first and last weeks
    record_seconds: 604800
  M:
    name: "monthly"
    freq: "M" # this is the freq code for pandas PeriodIndex. For DatetimeIndex, it's "MS".
    search_resolution: "D"
    result_resolution: "M"
    fixed: False # a monthly frequency is not a fixed number of days duration, it's based on the calendar month
    max_records: .inf
    record_seconds: 2419200 # minimum, 28 days. Maximum is 2678400, 31 days.

api_granularity_overrides:
  scrapingdog: # There are no overrides for scrapingdog, they are actually doing this right. They are 3 times as fast as searchapi!
  searchapi: # There are no overrides for searchapi, they are actually doing this right
  brightdata: # There are no overrides for brightdata, they are actually doing this right. They are VERY slow though. About 9 times longer than searchapi.
  serpapi:   # serpapi has a hard-coded day limit of 7 for hourly, which is wrong, but this will avoid errors on our searches.
    h:
      name: "hourly"
      freq: "h"
      search_resolution: "h"
      result_resolution: "h"
      fixed: True
      max_records: 168
      record_seconds: 3600
  serpwow:
    m:
      name: "one-minute"
      freq: "min"
      limit_units: "min"
      limit_value: 4
      search_resolution: "h"
      result_resolution: "m"
      fixed: True
      max_records: 0 # nothing below daily allowed by serpwow
      record_seconds: 3600
    e:
      name: "eight-minute"
      freq: "8min"
      limit_units: "8min"
      limit_value: 35
      search_resolution: "h"
      result_resolution: "m"
      fixed: True
      max_records: 0 # nothing below daily allowed by serpwow
      record_seconds: 3600
    n:
      name: "sixteen-minute"
      freq: "16min"
      limit_units: "16min"
      limit_value: 71
      search_resolution: "h"
      result_resolution: "m"
      fixed: True
      max_records: 0 # nothing below daily allowed by serpwow
      record_seconds: 3600
    h:
      name: "hourly"
      freq: "h"
      search_resolution: "h"
      result_resolution: "h"
      fixed: True
      max_records: 0 # nothing below daily allowed by serpwow
      record_seconds: 3600



# The max_records for 1 minute granularity (m) is 241 because
# 240 * 1 minutes = 240 minutes = 4 hours.
# It has to be less than 5 hours and it only goes by hours,
# so that means the longest search we can request is 4 hours.
# So the longest set of periods is 240 of 1 minute periods (4 hours exactly),
# and then the number of data points is 241 because the data includes both the start and end points.

# The max_records for 8 minute granularity (e) is 263 because
# 262 * 8 minutes = 2096 minutes = 34 hours 56 minutes.
# It has to be less than 36 hours and it only goes by hours,
# so that means the longest search we can request is 35 hours,
# which is not an even multiple of 8 minutes.
# So the longest set of periods is 262 of 8 minute periods (34 hours 56 minutes),
# and then the number of data points is 263 because the data includes both the start and end points.

# The max_records for 16 minute granularity (n) is 267 because
# 266 * 16 minutes = 4256 minutes = 70 hours 56 minutes.
# It has to be less than 72 hours and it only goes by hours,
# so that means the longest search we can request is 71 hours,
# which is not an even multiple of 16 minutes.
# So the longest set of periods is 266 of 16 minute periods (70 hours 56 minutes),
# and then the number of data points is 267 because the data includes both the start and end points.

# Here is what I based this on, although I believe I have corrected some errors.
# The complete list of granularities taken from github/sdil87/trendspy/src/trendspytimeframe_utils.py
# although I disagree with some of their non-inclusive max limits
# (i.e. I say <= 270 days instead of <270 days
# because we can certainly get search results that have 270 day records in them)
# <5 hours: 1 minute
# <36 hours: 8 minutes
# <72 hours: 16 minutes
# <8 days: 1 hour
# <270 days: 1 day
# <1900 days: 1 week
# <inf days: 1 month (as calendar months!!!)


# I am going to have to change this! The limits are not just by days.
# Each limit has to have limit_units and limit_value.
# The limit_units will be hours for the shorter ones, then days, then whole weeks, then whole months.
# This will eliminate the need for the max_inclusive flag.
# The application of these rules will require the use of pandas PeriodIndex
# because the rules are not just about the number of days, but also about the calendar month and week.
# this would be done in 

# Then another thing to do would be to use dummy data that is actual trends data.
# This would actually be easier, but not really until after I have the stagger part working so I can get the data.

# NOTE!! There is a bug in SerpAPI. Maximum search with hours is 2020-01-01T00 2020-01-07T23 but it should be 2020-01-01T00 2020-01-08T23.
# Verified that the latter works directly in Google Trends as of 2025-07-23.
# There may be other bugs in other APIs too.
